#!/bin/bash -x
WEBFS_VERSION=1.0.0

CURRDIR=$(pwd)
JAVA_WS=java-ws
WS_APP_PROPERTIES=./config/application.properties
WS_SCRIPT_SH=./scripts/start-webfs-service.sh
WS_SCRIPT_BAT=./scripts/start-webfs-service.bat
WS_WAR=./build/libs/webfs-service-$WEBFS_VERSION.war
WS_WAR_NAME=webfs-service.war

CONFIG_DIR=config
OUTPUT_ROOT=../../output
WS_OUTPUT_DIR=$OUTPUT_ROOT/$JAVA_WS
WS_PACKAGE_NAME=$JAVA_WS.$WEBFS_VERSION
WS_PACKAGE_NAME_ZIP=$JAVA_WS.$WEBFS_VERSION.zip

mkdir -p $WS_OUTPUT_DIR

# Web Service
rm -rf $WS_OUTPUT_DIR/$WS_PACKAGE_NAME
mkdir -p $WS_OUTPUT_DIR/$WS_PACKAGE_NAME
mkdir -p $WS_OUTPUT_DIR/$WS_PACKAGE_NAME/$CONFIG_DIR
cp $WS_SCRIPT_BAT $WS_OUTPUT_DIR/$WS_PACKAGE_NAME
cp $WS_SCRIPT_SH $WS_OUTPUT_DIR/$WS_PACKAGE_NAME
cp $WS_WAR $WS_OUTPUT_DIR/$WS_PACKAGE_NAME/$WS_WAR_NAME
cp $WS_APP_PROPERTIES $WS_OUTPUT_DIR/$WS_PACKAGE_NAME/$CONFIG_DIR
dos2unix $WS_OUTPUT_DIR/$WS_PACKAGE_NAME/$CONFIG_DIR/$WS_APP_PROPERTIES
cp README.txt $WS_OUTPUT_DIR/$WS_PACKAGE_NAME/README.txt
cd $WS_OUTPUT_DIR/$WS_PACKAGE_NAME
zip -r ../$WS_PACKAGE_NAME.zip *
cd $CURRDIR